start = """This tool allows you to translate CSS styles from the format generated by m3.material.io to the format used in @difhel projects (such as the SDFUI library - https://github.com/nacteam/sdfui).
To start, you need to generate a theme by selecting 3 key colors on the Material Theme Builder website - https://m3.material.io/theme-builder).
"""
locale_1 = "[1] Did you generate and download the theme archive? [y/n]: "
locale_2 = "[2] Enter the path to your ZIP archive or unzipped folder: "
copyright = """/* Generated automatically by material-theme-translator (https://github.com/difhel/material-theme-translator)
Author: Mark Fomin aka @difhel (email material-theme-translator@difhel.dev)
2023
* /
"""